# Generated by Django 3.1.5 on 2021-10-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('data', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Doador',
                'verbose_name_plural': 'Doador',
            },
        ),
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Dúvida frequente',
                'verbose_name_plural': 'Dúvidas frequentes',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do produto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.IntegerField(verbose_name='Preço')),
                ('disponivel', models.CharField(max_length=50, verbose_name='Disponível')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produto',
            },
        ),
        migrations.RemoveField(
            model_name='filme',
            name='atores',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='filme',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='sala',
        ),
        migrations.DeleteModel(
            name='Ator',
        ),
        migrations.DeleteModel(
            name='Filme',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
        migrations.DeleteModel(
            name='Sessao',
        ),
    ]
