# Generated by Django 3.1.5 on 2021-10-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20211028_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doador',
            options={'verbose_name': 'Doador', 'verbose_name_plural': 'Doadores'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='doador',
            name='senha',
            field=models.CharField(default='', max_length=120, verbose_name='Senha'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='sobre',
            field=models.CharField(default='', max_length=1000, verbose_name='Sobre'),
        ),
    ]
