# Generated by Django 3.1.5 on 2021-11-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20211108_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='fotoCapa',
            field=models.ImageField(max_length=255, null=True, upload_to='instituicoes'),
        ),
    ]
