# Generated by Django 3.1.5 on 2021-11-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_instituicao_fotocapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fotoCapa',
            field=models.ImageField(max_length=255, null=True, upload_to='produtos'),
        ),
    ]
