# Generated by Django 3.1.5 on 2021-11-22 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0009_produto_fotocapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doador',
            name='senha',
        ),
        migrations.AddField(
            model_name='doador',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário logado'),
        ),
    ]
