# Generated by Django 3.1.5 on 2021-11-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20211122_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizado', models.BooleanField()),
                ('doador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.doador', verbose_name='Doador')),
            ],
        ),
        migrations.DeleteModel(
            name='Cesta',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='item',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.pedido', verbose_name='Pedido'),
        ),
    ]
