# Generated by Django 3.1.5 on 2021-11-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20211122_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
