# Generated by Django 3.2.9 on 2021-11-29 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_item_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='instituicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.instituicao', verbose_name='Instituicao'),
        ),
    ]
